/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bmr_main_package;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Krzysztof
 */
public class SettingsForm extends javax.swing.JDialog
{

    // Class attributes
    private Settings settings = null;
    private boolean dataSaved = false;

    /**
     * Creates new form SettingsForm
     */
    public SettingsForm(Settings settings)
    {
        this.settings = settings;
        initComponents();

        SettingsToScreen(CommonDefs.FIELDS_COPY.DATA_TO_FIELDS);
    }

    public SettingsForm(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    // Access to class attributes and classs functions
    public boolean isSaved()
    {
        return this.dataSaved;
    }

    public Settings getSettings()
    {
        return this.settings;
    }

    // Settings from Data to Screen or from Screen to Data
    private void SettingsToScreen(CommonDefs.FIELDS_COPY fieldsCopy)
    {
        if (this.settings == null)
        {
            return;
        }

        switch (fieldsCopy)
        {
            case FIELDS_TO_DATA:
                this.settings.setName(this.txtName.getText());
                this.settings.setMeasuresXmlFile(this.txtFile.getText());
                this.settings.setMeasureScope(this.comboScope.getSelectedItem().toString());
                break;

            case DATA_TO_FIELDS:
                String scope = null;
                String combo = null;

                this.txtName.setText(this.settings.getName());
                this.txtFile.setText(this.settings.getMeasuresXmlFile());
                scope = this.settings.getMeasureScope();
                for (int idx = 0; idx < this.comboScope.getItemCount(); idx++)
                {
                    combo = this.comboScope.getItemAt(idx);
                    if (scope.equals(combo))
                    {
                        this.comboScope.setSelectedIndex(idx);
                    }
                }
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panelSettings = new javax.swing.JPanel();
        labName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        labFile = new javax.swing.JLabel();
        txtFile = new javax.swing.JTextField();
        butFile = new javax.swing.JButton();
        comboScope = new javax.swing.JComboBox<>();
        labScope = new javax.swing.JLabel();
        butSaveSettings = new javax.swing.JButton();
        butCancelSettings = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setResizable(false);

        labName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labName.setText("Name:");
        labName.setToolTipText("Your name");

        txtName.setToolTipText("Your name");

        labFile.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labFile.setText("Measures file:");
        labFile.setToolTipText("File containing blood measures");

        txtFile.setToolTipText("File containig blood measures");

        butFile.setText("...");
        butFile.setToolTipText("Select file");
        butFile.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                butFileActionPerformed(evt);
            }
        });

        comboScope.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRESSURE", "GLUCOSE", "ALL" }));
        comboScope.setToolTipText("Scope of registered measures: blood pressure, glucose, both");

        labScope.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labScope.setText("Scope:");

        butSaveSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmr_main_package/Icons/save-icon.png"))); // NOI18N
        butSaveSettings.setToolTipText("Save data");
        butSaveSettings.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                butSaveSettingsActionPerformed(evt);
            }
        });

        butCancelSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmr_main_package/Icons/Actions-button-cancel-icon.png"))); // NOI18N
        butCancelSettings.setToolTipText("Save data");
        butCancelSettings.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                butCancelSettingsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSettingsLayout = new javax.swing.GroupLayout(panelSettings);
        panelSettings.setLayout(panelSettingsLayout);
        panelSettingsLayout.setHorizontalGroup(
            panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSettingsLayout.createSequentialGroup()
                .addGroup(panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSettingsLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labScope, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labFile, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboScope, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelSettingsLayout.createSequentialGroup()
                                .addGroup(panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFile, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                                    .addComponent(txtName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(butFile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelSettingsLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(butSaveSettings)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(butCancelSettings)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panelSettingsLayout.setVerticalGroup(
            panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSettingsLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labFile)
                    .addComponent(txtFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labScope)
                    .addComponent(comboScope, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butSaveSettings)
                    .addComponent(butCancelSettings))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butFileActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_butFileActionPerformed
    {//GEN-HEADEREND:event_butFileActionPerformed
        FileFilter filter = new FileNameExtensionFilter("XML files", "xml");
        JFileChooser fileChooser = new JFileChooser();

        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        fileChooser.setDialogTitle("Select XML file containing your blood measures");
        fileChooser.setMultiSelectionEnabled(false);
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        fileChooser.setFileFilter(filter);

        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION)
        {
            File selectedFile = fileChooser.getSelectedFile();
            this.txtFile.setText(selectedFile.getAbsolutePath());
        }
    }//GEN-LAST:event_butFileActionPerformed

    private void butSaveSettingsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_butSaveSettingsActionPerformed
    {//GEN-HEADEREND:event_butSaveSettingsActionPerformed
        SettingsToScreen(CommonDefs.FIELDS_COPY.FIELDS_TO_DATA);
        this.dataSaved = true;
        this.dispose();
    }//GEN-LAST:event_butSaveSettingsActionPerformed

    private void butCancelSettingsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_butCancelSettingsActionPerformed
    {//GEN-HEADEREND:event_butCancelSettingsActionPerformed
        this.dispose();
    }//GEN-LAST:event_butCancelSettingsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void umain(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(SettingsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(SettingsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(SettingsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(SettingsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                SettingsForm dialog = new SettingsForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCancelSettings;
    private javax.swing.JButton butFile;
    private javax.swing.JButton butSaveSettings;
    private javax.swing.JComboBox<String> comboScope;
    private javax.swing.JLabel labFile;
    private javax.swing.JLabel labName;
    private javax.swing.JLabel labScope;
    private javax.swing.JPanel panelSettings;
    private javax.swing.JTextField txtFile;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
